spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true # CRÍTICO: Para que funcione antes de las rutas
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        # CUSTOMER
        - id: ms-customer-sub
          uri: lb://MS-CUSTOMER
          predicates:
            - Path=/api/customers/**

        # KARDEX
        - id: ms-kardex-route
          uri: lb://MS-KARDEX
          predicates:
            - Path=/api/kardex/**