server.port=8085
spring.application.name=api-gateway

# Esto permite que el Gateway cree rutas automáticamente basadas en Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Configuración de Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

